export const cardData = [
    {
        id:1,
        backgroundColor:"#FEE4EE",
        src:"/pariImage/card1.png",
        heading:"Regular Fit ling sleeves suit",
        price:"$38.99",
        rating:"5.0",
    },
    {
        id:2,
        backgroundColor:"#FEE4EE",
        src:"/pariImage/card2.png",
        heading:"Regular Fit ling sleeves suit",
        price:"$38.99",
        rating:"5.0",
    },
    {
        id:3,
        backgroundColor:"#FEE4EE",
        src:"/pariImage/card3.png",
        heading:"Regular Fit ling sleeves suit",
        price:"$38.99",
        rating:"5.0",
    },
    {
        id:4,
        backgroundColor:"#FEE4EE",
        src:"/pariImage/card4.png",
        heading:"Regular Fit ling sleeves suit",
        price:"$38.99",
        rating:"5.0",
    },
    {
        id:5,
        backgroundColor:"#FEE4EE",
        src:"/pariImage/card5.png",
        heading:"Regular Fit ling sleeves suit",
        price:"$38.99",
        rating:"5.0",
    },
    {
        id:6,
        backgroundColor:"#FEE4EE",
        src:"/pariImage/card6.png",
        heading:"Regular Fit ling sleeves suit",
        price:"$38.99",
        rating:"5.0",
    },
]